import { Component, OnInit, ViewChild, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { AdminShellComponent } from './admin-shell.component';
import { BlogBodyEditorComponent } from '../../shared/blog-body-editor.component';
import { ApiService, BlogListItem, BlogDetail, BlogCategory, BlogUpsert, PexelsPhoto } from '../../core/services/api.service';

/**
 * Admin for the blog: a Posts directory + WYSIWYG editor (rich-text body,
 * featured image, category, SEO, pin, schedule, Edit-with-AI, live preview) and
 * a Categories manager. Posts are generated by the shared keyword pipeline
 * (ContentType=Post) and edited/published here. Single voice, one category each.
 */
@Component({
  selector: 'app-admin-blog',
  standalone: true,
  imports: [CommonModule, FormsModule, AdminShellComponent, BlogBodyEditorComponent],
  template: `
    <app-admin-shell active="blog">
      <div class="bpa">
        <div class="bpa-tabs">
          <button class="bpa-tab" [class.on]="tab() === 'posts'" (click)="tab.set('posts')">Posts</button>
          <button class="bpa-tab" [class.on]="tab() === 'categories'" (click)="tab.set('categories'); loadCategories()">Categories</button>
        </div>

        <!-- ── POSTS: directory ── -->
        @if (tab() === 'posts' && !editing()) {
          <div class="bpa-bar">
            <input class="bpa-input" placeholder="Search title, keyword, slug…" [(ngModel)]="search" (keyup.enter)="loadPosts()">
            <select class="bpa-input bpa-input--sm" [(ngModel)]="statusFilter" (change)="loadPosts()">
              <option value="">All statuses</option><option value="Published">Published</option><option value="Draft">Draft</option><option value="Archived">Archived</option>
            </select>
            <select class="bpa-input bpa-input--sm" [(ngModel)]="categoryFilter" (change)="loadPosts()">
              <option value="">All categories</option>
              @for (c of categories(); track c.id) { <option [value]="c.slug">{{ c.name }}</option> }
            </select>
            <button class="bpa-btn" (click)="newPost()">+ New post</button>
          </div>
          @if (!posts().length) { <p class="bpa-muted">No posts yet. Queue a keyword as a <strong>Post</strong> and let the daily generator write one — or create one manually.</p> }
          @else {
            <table class="bpa-table">
              <thead><tr><th>Title</th><th>Category</th><th>Status</th><th></th></tr></thead>
              <tbody>
                @for (p of posts(); track p.id) {
                  <tr>
                    <td class="bpa-title">{{ p.title || '—' }}@if (p.pinned) { <span class="bpa-pill bpa-pill--pin">pinned</span> }@if (p.noIndex) { <span class="bpa-pill bpa-pill--mute">noindex</span> }
                      <div class="bpa-sub2">{{ p.readingTimeMinutes }} min · {{ p.targetKeyword }}</div></td>
                    <td class="bpa-muted">{{ p.categoryName }}</td>
                    <td>
                      <span class="bpa-pill" [class.bpa-pill--pub]="p.status==='Published'" [class.bpa-pill--draft]="p.status==='Draft'">{{ p.status }}</span>
                      @if (p.scheduledFor && p.status !== 'Published') { <span class="bpa-pill bpa-pill--sched">scheduled</span> }
                    </td>
                    <td class="bpa-actions">
                      <button class="bpa-link" (click)="edit(p)">Edit</button>
                      <button class="bpa-link" (click)="preview(p.id)">Preview</button>
                      @if (p.status === 'Published') { <button class="bpa-link" (click)="setStatus(p,'Archived')">Unpublish</button> }
                      @else { <button class="bpa-link" (click)="setStatus(p,'Published')">Publish</button> }
                      <button class="bpa-link bpa-link--danger" (click)="del(p)">Delete</button>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
            <p class="bpa-muted">{{ total() }} posts</p>
          }
        }

        <!-- ── POSTS: editor ── -->
        @if (tab() === 'posts' && editing(); as e) {
          <div class="bpa-bar">
            <button class="bpa-link" (click)="closeEditor()">← Back</button>
            <span class="bpa-spacer"></span>
            @if (msg()) { <span class="bpa-ok">{{ msg() }}</span> }
            @if (e.hasOriginal && e.generatedByAi) { <button class="bpa-link" (click)="revert(e.id)">Revert to AI original</button> }
            <button class="bpa-link" (click)="e.id && preview(e.id)" [disabled]="!e.id">Preview</button>
            <button class="bpa-btn" [disabled]="saving()" (click)="save()">{{ saving() ? 'Saving…' : 'Save' }}</button>
          </div>
          @if (editError()) { <p class="bpa-err">{{ editError() }}</p> }

          <div class="bpe-split">
          <div class="bpe-form">
            @if (e.id) {
            <div class="bpa-card bpa-ai">
              <h3>✨ Edit with AI</h3>
              <p class="bpa-hint" style="margin-top:0">Describe a change to the body, FAQ, or CTA. Stays inside the template; review the diff before it applies.</p>
              <textarea class="bpa-input" rows="2" placeholder="e.g. Add a section on overcoming perfectionism, and tighten the intro." [(ngModel)]="aiInstruction"></textarea>
              <div class="bpa-row" style="margin-top:.5rem; flex-wrap:wrap; align-items:center">
                <button class="bpa-btn" [disabled]="aiBusy() || !aiInstruction.trim()" (click)="runAiEdit()">{{ aiBusy() ? 'Thinking…' : 'Propose changes' }}</button>
                @if (e.hasPrevious) { <button class="bpa-link" (click)="undo(e.id)">↩ Undo last edit</button> }
              </div>
              @if (aiError()) { <p class="bpa-err">{{ aiError() }}</p> }
              @if (aiChanges().length) {
                <div class="bpa-diff">
                  @for (c of aiChanges(); track $index) { <div class="bpa-diff__l" [class.add]="c.startsWith('+')" [class.del]="c.startsWith('-')">{{ c }}</div> }
                  <div class="bpa-row" style="margin-top:.6rem"><button class="bpa-btn" (click)="acceptAiEdit()">Accept changes</button><button class="bpa-link" (click)="discardAiEdit()">Discard</button></div>
                </div>
              }
            </div>
            }

            <div class="bpa-card">
              <h3>Post</h3>
              <label class="bpa-f"><span>Title (H1)</span><input class="bpa-input" [(ngModel)]="e.title"></label>
              <label class="bpa-f"><span>Standfirst / dek</span><input class="bpa-input" [(ngModel)]="e.dek"></label>
              <label class="bpa-f"><span>Category</span>
                <select class="bpa-input" [(ngModel)]="e.categoryId">@for (c of categories(); track c.id) { <option [ngValue]="c.id">{{ c.name }}</option> }</select></label>
            </div>

            <div class="bpa-card">
              <h3>Featured image</h3>
              <label class="bpa-f"><span>Image URL <button type="button" class="bpa-imgbtn" (click)="openImg('featured')">🔍 Find photo</button></span><input class="bpa-input" [(ngModel)]="e.featuredImageUrl"></label>
              @if (e.featuredImageUrl) { <img class="bpa-thumb" [src]="e.featuredImageUrl" alt=""> }
              <label class="bpa-f"><span>Alt text</span><input class="bpa-input" [(ngModel)]="e.featuredImageAlt"></label>
            </div>

            <div class="bpa-card">
              <h3>Body</h3>
              <app-blog-body-editor [html]="e.content.bodyHtml" (htmlChange)="e.content.bodyHtml = $event" (requestImage)="openImg('body')"></app-blog-body-editor>
            </div>

            <div class="bpa-card">
              <h3>FAQ</h3>
              @for (q of e.content.faq; track $index) {
                <div class="bpa-sub"><div class="bpa-row"><input class="bpa-input" placeholder="Question" [(ngModel)]="q.q"><button class="bpa-x" (click)="e.content.faq.splice($index,1)">×</button></div>
                  <textarea class="bpa-input" rows="2" placeholder="Answer" [(ngModel)]="q.a"></textarea></div>
              }
              <button class="bpa-add" (click)="e.content.faq.push({})">+ question</button>
            </div>

            <div class="bpa-card">
              <h3>Call to action</h3>
              <label class="bpa-f"><span>Heading</span><input class="bpa-input" [(ngModel)]="e.content.ctaHeading" placeholder="Keep the chain alive — one small step a day."></label>
              <label class="bpa-f"><span>Button label</span><input class="bpa-input" [(ngModel)]="e.content.ctaLabel" placeholder="Start your free 10-day trial"></label>
            </div>

            <div class="bpa-card">
              <h3>SEO &amp; URL</h3>
              <label class="bpa-f"><span>Target keyword</span><input class="bpa-input" [(ngModel)]="e.targetKeyword"></label>
              <label class="bpa-f"><span>Slug <em>/blog/{{ e.categorySlug }}/{{ e.slug }}</em></span><input class="bpa-input" [(ngModel)]="e.slug"></label>
              <label class="bpa-f"><span>Meta title <em>{{ (e.metaTitle||'').length }}/60</em></span><input class="bpa-input" [(ngModel)]="e.metaTitle"></label>
              <label class="bpa-f"><span>Meta description <em>{{ (e.metaDescription||'').length }}/155</em></span><textarea class="bpa-input" rows="2" [(ngModel)]="e.metaDescription"></textarea></label>
              <label class="bpa-f"><span>Canonical URL override</span><input class="bpa-input" [(ngModel)]="e.canonicalUrl" placeholder="(auto)"></label>
              <label class="bpa-check"><input type="checkbox" [(ngModel)]="e.noIndex"> noindex (keep out of search + sitemap)</label>
            </div>

            <div class="bpa-card">
              <h3>Publishing</h3>
              <label class="bpa-check"><input type="checkbox" [(ngModel)]="e.pinned"> Pin to top of blog/category lists</label>
              @if (e.pinned) { <label class="bpa-f"><span>Pinned position (lower = first)</span><input class="bpa-input bpa-input--sm" type="number" [(ngModel)]="e.pinnedPosition"></label> }
              <label class="bpa-f"><span>Schedule publish (optional)</span><input class="bpa-input bpa-input--sm" type="datetime-local" [(ngModel)]="scheduledLocal"></label>
              <p class="bpa-hint">If set on a draft, the post auto-publishes at that time. Leave blank to publish manually.</p>
            </div>
          </div>

          <div class="bpe-preview">
            @if (previewUrl()) {
              <p class="bpe-tip">Live preview of the rendered post. <strong>Save</strong> to refresh it.</p>
              <iframe class="bpe-frame" [src]="previewUrl()" title="Live preview"></iframe>
            } @else { <p class="bpa-muted" style="padding:1rem">Save the post to open the live preview here.</p> }
          </div>
          </div>
        }

        <!-- ── CATEGORIES ── -->
        @if (tab() === 'categories') {
          <div class="bpa-card">
            <h3>Add a category</h3>
            <div class="bpa-row"><input class="bpa-input" placeholder="Name (e.g. Overcoming Blocks)" [(ngModel)]="newCat.name">
              <input class="bpa-input bpa-input--sm" type="number" placeholder="Pos" [(ngModel)]="newCat.position">
              <button class="bpa-btn" [disabled]="!newCat.name.trim()" (click)="addCategory()">Add</button></div>
            <input class="bpa-input" placeholder="Description (optional, shown on the category page)" [(ngModel)]="newCat.description" style="margin-top:.5rem">
            @if (catMsg()) { <span class="bpa-ok">{{ catMsg() }}</span> }
          </div>
          <table class="bpa-table">
            <thead><tr><th>Pos</th><th>Category</th><th>Slug</th><th>Posts</th><th></th></tr></thead>
            <tbody>
              @for (c of categories(); track c.id) {
                <tr>
                  <td><input class="bpa-input bpa-input--xs" type="number" [(ngModel)]="c.position" [disabled]="c.isSystem" (change)="saveCategory(c)"></td>
                  <td><input class="bpa-input" [(ngModel)]="c.name" [disabled]="c.isSystem" (change)="saveCategory(c)"></td>
                  <td><code>/{{ c.slug }}</code>@if (c.isSystem) { <span class="bpa-pill bpa-pill--mute">system</span> }</td>
                  <td>{{ c.postCount }}</td>
                  <td class="bpa-actions">@if (!c.isSystem) { <button class="bpa-link bpa-link--danger" (click)="delCategory(c)">Delete</button> }</td>
                </tr>
              }
            </tbody>
          </table>
          <p class="bpa-hint">Renaming a category's slug 301-redirects its old post URLs. Deleting moves its posts to Uncategorized (with redirects).</p>
        }

        <!-- ── IMAGE PICKER ── -->
        @if (imgOpen()) {
          <div class="bpa-modal" (click)="imgOpen.set(false)">
            <div class="bpa-modal__box" (click)="$event.stopPropagation()">
              <div class="bpa-row"><input class="bpa-input" placeholder="Search free photos (Pexels)…" [(ngModel)]="imgQuery" (keyup.enter)="searchImg()"><button class="bpa-btn" (click)="searchImg()">Search</button><button class="bpa-x" (click)="imgOpen.set(false)">×</button></div>
              @if (imgBusy()) { <p class="bpa-muted">Working…</p> }
              <div class="bpa-imggrid">
                @for (ph of imgResults(); track ph.id) {
                  <button class="bpa-imgcard" [disabled]="imgBusy()" (click)="chooseImg(ph)"><img [src]="ph.thumbUrl" [alt]="ph.alt" loading="lazy"><span>{{ ph.photographer }}</span></button>
                }
              </div>
              @if (!imgResults().length && !imgBusy()) { <p class="bpa-muted">Type a search and press enter. Photos are from Pexels (free, commercial use).</p> }
            </div>
          </div>
        }
      </div>
    </app-admin-shell>
  `,
  styles: [`
    .bpa { max-width: 1240px; margin: 0 auto; padding: 1.5rem; }
    .bpe-split { display: flex; gap: 1.25rem; align-items: flex-start; }
    .bpe-form { flex: 1 1 460px; min-width: 0; }
    .bpe-preview { flex: 1 1 520px; position: sticky; top: 1rem; align-self: flex-start; }
    .bpe-tip { font-size: .8rem; color: #0a6b7d; margin: 0 0 .5rem; background: #eef9fb; border: 1px solid #bdeef5; border-radius: 8px; padding: .5rem .75rem; }
    .bpe-frame { width: 100%; height: calc(100vh - 170px); min-height: 480px; border: 1px solid #e5e7eb; border-radius: 12px; background: #fff; }
    @media (max-width: 1080px) { .bpe-split { flex-direction: column; } .bpe-preview { position: static; width: 100%; } .bpe-frame { height: 72vh; } }
    .bpa-tabs { display: flex; gap: .5rem; margin-bottom: 1.25rem; border-bottom: 1px solid #e5e7eb; }
    .bpa-tab { background: none; border: none; padding: .6rem .9rem; font-weight: 700; color: #6b7280; cursor: pointer; border-bottom: 2px solid transparent; }
    .bpa-tab.on { color: #0c0e13; border-bottom-color: #12C4E3; }
    .bpa-bar { display: flex; align-items: center; gap: .5rem; margin-bottom: 1rem; flex-wrap: wrap; }
    .bpa-spacer { flex: 1; }
    .bpa-input { width: 100%; padding: .55rem .7rem; border: 1px solid #d1d5db; border-radius: 8px; font-size: .9375rem; font-family: inherit; }
    .bpa-input--sm { width: auto; min-width: 150px; flex: none; } .bpa-input--xs { width: 64px; flex: none; }
    .bpa-btn { background: #0c0e13; color: #fff; border: none; border-radius: 999px; padding: .55rem 1.1rem; font-weight: 700; cursor: pointer; white-space: nowrap; }
    .bpa-btn:disabled { opacity: .5; }
    .bpa-link { background: none; border: none; color: #0a93ab; font-weight: 600; cursor: pointer; padding: .2rem .4rem; }
    .bpa-link--danger { color: #e11d48; }
    .bpa-table { width: 100%; border-collapse: collapse; font-size: .9375rem; }
    .bpa-table th { text-align: left; color: #6b7280; font-size: .75rem; text-transform: uppercase; letter-spacing: .05em; padding: .4rem .5rem; border-bottom: 1px solid #e5e7eb; }
    .bpa-table td { padding: .55rem .5rem; border-bottom: 1px solid #f1f1f1; vertical-align: middle; }
    .bpa-title { font-weight: 600; } .bpa-sub2 { font-size: .72rem; color: #9ca3af; font-weight: 400; margin-top: .15rem; }
    .bpa-actions { white-space: nowrap; text-align: right; }
    .bpa-muted { color: #9ca3af; } .bpa-hint { font-size: .8rem; color: #9ca3af; margin: .5rem 0 0; }
    .bpa-pill { font-size: .7rem; font-weight: 700; padding: .15rem .5rem; border-radius: 999px; background: #eef0f2; color: #4b5563; margin-left: .35rem; }
    .bpa-pill--pub { background: #d1fae5; color: #047857; } .bpa-pill--draft { background: #fef3c7; color: #92400e; }
    .bpa-pill--mute { background: #f3f4f6; color: #9ca3af; } .bpa-pill--pin { background: #ede9fe; color: #6d28d9; } .bpa-pill--sched { background: #e0f2fe; color: #0369a1; }
    .bpa-card { background: #fff; border: 1px solid #e5e7eb; border-radius: 14px; padding: 1.25rem; margin-bottom: 1rem; }
    .bpa-card h3 { margin: 0 0 .9rem; font-size: 1rem; }
    .bpa-ai { border-color: #bdeef5; background: #f7fdfe; }
    .bpa-f { display: block; margin-bottom: .8rem; } .bpa-f span { display: block; font-size: .8125rem; font-weight: 700; margin-bottom: .25rem; color: #374151; }
    .bpa-f em { color: #9ca3af; font-weight: 400; font-style: normal; }
    .bpa-check { display: flex; align-items: center; gap: .5rem; font-size: .9rem; margin: .4rem 0; }
    .bpa-row { display: flex; gap: .5rem; align-items: flex-start; margin-bottom: .5rem; }
    .bpa-sub { border: 1px solid #eef0f2; border-radius: 10px; padding: .75rem; margin-bottom: .6rem; }
    .bpa-x { background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; width: 34px; flex: none; cursor: pointer; color: #e11d48; font-weight: 700; }
    .bpa-add { background: #f3f4f6; border: 1px dashed #d1d5db; border-radius: 8px; padding: .4rem .8rem; font-weight: 600; color: #4b5563; cursor: pointer; }
    .bpa-ok { color: #047857; font-weight: 600; } .bpa-err { color: #e11d48; }
    .bpa-imgbtn { background: #eef9fb; border: 1px solid #bdeef5; color: #0a93ab; border-radius: 8px; padding: .15rem .5rem; font-size: .75rem; font-weight: 700; cursor: pointer; margin-left: .5rem; }
    .bpa-thumb { width: 100%; max-height: 160px; object-fit: cover; border-radius: 10px; margin: 0 0 .6rem; }
    .bpa-diff { margin-top: .8rem; border: 1px solid #e5e7eb; border-radius: 10px; padding: .75rem; }
    .bpa-diff__l { font-size: .85rem; padding: .2rem 0; color: #374151; } .bpa-diff__l.add { color: #047857; } .bpa-diff__l.del { color: #b91c1c; }
    .bpa-modal { position: fixed; inset: 0; background: rgba(12,14,19,.5); display: grid; place-items: center; z-index: 1000; padding: 1.5rem; }
    .bpa-modal__box { background: #fff; border-radius: 16px; padding: 1.25rem; width: 100%; max-width: 720px; max-height: 84vh; overflow: auto; }
    .bpa-imggrid { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); gap: .6rem; margin-top: .8rem; }
    .bpa-imgcard { border: 1px solid #e5e7eb; border-radius: 10px; overflow: hidden; background: #fff; cursor: pointer; padding: 0; text-align: left; }
    .bpa-imgcard img { width: 100%; height: 110px; object-fit: cover; display: block; }
    .bpa-imgcard span { display: block; font-size: .7rem; color: #9ca3af; padding: .3rem .5rem; }
    code { font-size: .85em; color: #4b5563; }
  `]
})
export class AdminBlogComponent implements OnInit {
  private api = inject(ApiService);
  private sanitizer = inject(DomSanitizer);
  @ViewChild(BlogBodyEditorComponent) bodyEditor?: BlogBodyEditorComponent;

  tab = signal<'posts' | 'categories'>('posts');
  saving = signal(false); msg = signal(''); editError = signal('');
  posts = signal<BlogListItem[]>([]); total = signal(0);
  search = ''; statusFilter = ''; categoryFilter = ''; sort = 'updated';
  editing = signal<BlogDetail | null>(null);
  categories = signal<BlogCategory[]>([]);
  newCat = { name: '', description: '', position: 0 };
  catMsg = signal('');
  previewUrl = signal<SafeResourceUrl | null>(null);
  scheduledLocal = '';

  // AI edit
  aiInstruction = ''; aiBusy = signal(false); aiError = signal(''); aiChanges = signal<string[]>([]);
  private aiProposed: BlogDetail['content'] | null = null;

  // Image picker
  imgOpen = signal(false); imgQuery = ''; imgResults = signal<PexelsPhoto[]>([]); imgBusy = signal(false);
  private imgTarget: 'featured' | 'body' = 'featured';

  ngOnInit(): void { this.loadCategories(); this.loadPosts(); }

  loadPosts(): void {
    this.api.adminBlogList({ search: this.search, status: this.statusFilter, category: this.categoryFilter, sort: this.sort, take: 100 })
      .subscribe(r => { this.posts.set(r.items); this.total.set(r.total); });
  }
  loadCategories(): void { this.api.adminBlogCategories().subscribe(c => this.categories.set(c)); }

  private blankContent() { return { bodyHtml: '', faq: [] as { q?: string; a?: string }[], ctaHeading: '', ctaLabel: '' }; }
  private hydrate(d: BlogDetail): BlogDetail { d.content = d.content || this.blankContent(); d.content.faq = d.content.faq || []; return d; }

  newPost(): void {
    this.editError.set(''); this.msg.set(''); this.previewUrl.set(null); this.scheduledLocal = '';
    const catId = this.categories()[0]?.id ?? '';
    const catSlug = this.categories()[0]?.slug ?? 'uncategorized';
    this.editing.set({
      id: '', slug: '', status: 'Draft', categoryId: catId, categorySlug: catSlug, targetKeyword: '', title: '', dek: '',
      metaTitle: '', metaDescription: '', canonicalUrl: '', noIndex: false, featuredImageUrl: '', featuredImageAlt: '',
      snippet: '', readingTimeMinutes: 0, pinned: false, pinnedPosition: null, content: this.blankContent(),
      hasOriginal: false, hasPrevious: false, qualityScore: null, generatedByAi: false, publishDate: null, scheduledFor: null,
      lastUpdatedAt: '', createdAt: '', updatedAt: '', publishedAt: null,
    });
  }

  edit(p: BlogListItem): void {
    this.editError.set(''); this.msg.set(''); this.previewUrl.set(null);
    this.api.adminBlogGet(p.id).subscribe(d => { this.editing.set(this.hydrate(d)); this.scheduledLocal = toLocalInput(d.scheduledFor); this.loadPreview(d.id); });
  }

  closeEditor(): void { this.editing.set(null); this.previewUrl.set(null); this.loadPosts(); }

  save(): void {
    const e = this.editing(); if (!e) return;
    this.saving.set(true); this.editError.set('');
    const payload: BlogUpsert = {
      slug: e.slug, categoryId: e.categoryId, targetKeyword: e.targetKeyword, title: e.title, dek: e.dek,
      metaTitle: e.metaTitle, metaDescription: e.metaDescription, canonicalUrl: e.canonicalUrl, noIndex: e.noIndex,
      featuredImageUrl: e.featuredImageUrl, featuredImageAlt: e.featuredImageAlt, snippet: e.snippet,
      pinned: e.pinned, pinnedPosition: e.pinnedPosition, scheduledFor: fromLocalInput(this.scheduledLocal), content: e.content,
    };
    const obs = e.id ? this.api.adminBlogUpdate(e.id, payload) : this.api.adminBlogCreate(payload);
    obs.subscribe({
      next: d => { this.editing.set(this.hydrate(d)); this.scheduledLocal = toLocalInput(d.scheduledFor); this.saving.set(false); this.msg.set('Saved.'); setTimeout(() => this.msg.set(''), 2000); this.reloadPreview(d.id); },
      error: err => { this.saving.set(false); this.editError.set(err?.error?.error ?? 'Save failed.'); },
    });
  }

  setStatus(p: BlogListItem, status: string): void { this.api.adminBlogSetStatus(p.id, status).subscribe(() => this.loadPosts()); }
  del(p: BlogListItem): void { if (confirm(`Delete "${p.title || p.slug}"? It will 410 for crawlers.`)) this.api.adminBlogDelete(p.id).subscribe(() => this.loadPosts()); }
  revert(id: string): void { if (confirm('Discard your edits and restore the AI original?')) this.api.adminBlogRevert(id).subscribe(d => { this.editing.set(this.hydrate(d)); this.msg.set('Reverted.'); this.reloadPreview(id); }); }
  undo(id: string): void { this.api.adminBlogUndo(id).subscribe(d => { this.editing.set(this.hydrate(d)); this.msg.set('Undid last edit.'); setTimeout(() => this.msg.set(''), 2500); this.reloadPreview(id); }); }
  preview(id: string): void { this.api.adminBlogPreview(id).subscribe(r => window.open(r.url, '_blank')); }

  private loadPreview(id: string): void { this.api.adminBlogPreview(id).subscribe(r => this.previewUrl.set(this.sanitizer.bypassSecurityTrustResourceUrl(r.url))); }
  private reloadPreview(id: string): void {
    // Re-point the iframe with a cache-busting param so the saved render shows.
    this.api.adminBlogPreview(id).subscribe(r => this.previewUrl.set(this.sanitizer.bypassSecurityTrustResourceUrl(r.url + '&t=' + Date.now())));
  }

  // AI edit
  runAiEdit(): void {
    const e = this.editing(); if (!e?.id || !this.aiInstruction.trim()) return;
    this.aiBusy.set(true); this.aiError.set(''); this.aiChanges.set([]); this.aiProposed = null;
    this.api.adminBlogAiEdit(e.id, this.aiInstruction.trim()).subscribe({
      next: p => { this.aiBusy.set(false); this.aiProposed = p.content; this.aiChanges.set(p.changes.length ? p.changes : ['Updated the post content.']); },
      error: err => { this.aiBusy.set(false); this.aiError.set(err?.error?.error ?? 'Could not generate that edit.'); },
    });
  }
  acceptAiEdit(): void {
    const e = this.editing(); if (!e || !this.aiProposed) return;
    e.content = { ...this.aiProposed, faq: this.aiProposed.faq || [] };
    this.editing.set({ ...e });
    this.discardAiEdit(); this.aiInstruction = '';
    this.save();
  }
  discardAiEdit(): void { this.aiChanges.set([]); this.aiProposed = null; }

  // Categories
  addCategory(): void {
    if (!this.newCat.name.trim()) return;
    this.api.adminBlogCreateCategory({ name: this.newCat.name, description: this.newCat.description || null, position: this.newCat.position }).subscribe({
      next: () => { this.newCat = { name: '', description: '', position: 0 }; this.catMsg.set('Added.'); setTimeout(() => this.catMsg.set(''), 2000); this.loadCategories(); },
      error: err => this.catMsg.set(err?.error?.error ?? 'Could not add.'),
    });
  }
  saveCategory(c: BlogCategory): void {
    this.api.adminBlogUpdateCategory(c.id, { name: c.name, slug: c.slug, description: c.description, position: c.position }).subscribe({ error: () => this.loadCategories() });
  }
  delCategory(c: BlogCategory): void {
    if (!confirm(`Delete "${c.name}"? Its posts move to Uncategorized (with redirects).`)) return;
    this.api.adminBlogDeleteCategory(c.id).subscribe({ next: () => this.loadCategories(), error: err => alert(err?.error?.error ?? 'Could not delete.') });
  }

  // Image picker
  openImg(target: 'featured' | 'body'): void { this.imgTarget = target; this.imgResults.set([]); this.imgQuery = ''; this.imgOpen.set(true); }
  searchImg(): void {
    if (!this.imgQuery.trim()) return;
    this.imgBusy.set(true);
    this.api.adminLpSearchImages(this.imgQuery).subscribe({ next: r => { this.imgResults.set(r); this.imgBusy.set(false); }, error: () => this.imgBusy.set(false) });
  }
  chooseImg(ph: PexelsPhoto): void {
    this.imgBusy.set(true);
    this.api.adminLpUseImage(ph.fullUrl).subscribe({
      next: r => {
        this.imgBusy.set(false); this.imgOpen.set(false);
        if (this.imgTarget === 'featured') { const e = this.editing(); if (e) { e.featuredImageUrl = r.url; if (!e.featuredImageAlt) e.featuredImageAlt = ph.alt; } }
        else this.bodyEditor?.insertImage(r.url, ph.alt);
      },
      error: () => this.imgBusy.set(false),
    });
  }
}

// datetime-local <-> ISO helpers (the input has no timezone; treat as local).
function toLocalInput(iso: string | null): string {
  if (!iso) return '';
  const d = new Date(iso); if (isNaN(d.getTime())) return '';
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
function fromLocalInput(local: string): string | null {
  if (!local) return null;
  const d = new Date(local); return isNaN(d.getTime()) ? null : d.toISOString();
}
